cp_appearance.custom_theme.*:
  type: config_entity
  label: 'Cp Custom Theme'
  mapping:
    id:
      type: 'string'
      label: 'Machine name'
    label:
      type: 'label'
      label: 'Label'
    base_theme:
      type: 'string'
      label: 'Base theme'
    favicon:
      type: integer
      label: 'Favicon'
    images:
      type: cp_appearance_custom_theme.images

cp_appearance_custom_theme.images:
  type: sequence
  label: 'Images'
  sequence:
    type: integer
    label: 'Image Id'
