language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  artifacts:
    s3_region: $ARTIFACTS_S3_REGION
    paths:
      - ./web/sites/simpletest
      - ./web/sites/default/files

services:
  - docker

php:
  - 7.2

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - TRAVIS_NODE_VERSION="4"
  matrix:
    - JOB=job:check-coding-standards
    - JOB=job:run-unit-tests
    - JOB="job:run-kernel-tests widgets,vsite"
    - JOB="job:run-kernel-tests os-theme-preview,cp-appearance,publications,os"
    - JOB="job:run-kernel-tests redirect,other,cp"
    - JOB="job:run-functional-tests classes,events,pages,publications,cp-appearance,os"
    - JOB="job:run-functional-tests cp,media-browser,os-theme-preview,vsite,breadcrumbs,analytics"
    - JOB="job:run-functional-javascript-tests classes,events,pages,publications,widgets,cp-appearance"
    - JOB="job:run-functional-javascript-tests cp,vsite,mailchimp,metatag,redirect,os-theme-preview"
#    - JOB=job:run-behat-tests

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer global require consolidation/robo

before_script:
  - cp .travis/RoboFile.php .

script:
  - robo $JOB

after_success:
  - bash <(curl -s https://codecov.io/bash)
